# Generated by Django 6.0 on 2026-01-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_time',
            field=models.IntegerField(default=0),
        ),
    ]
